Desktop/Hackathon/HACKOVERFLOW/NACOF/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^user_panel/', include('user_panel.urls')),
    url(r'^member_panel/', include('member_panel.urls')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^cart/',include('cart.urls')),
    url(r'^myorders/',include('myorders.urls'))

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/Hackathon/HACKOVERFLOW/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    
]

Desktop/Hackathon/HACKOVERFLOW/products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_to_cart/$',views.add_to_cart,name='add_to_cart'),
    url(r'^mycart/$',views.mycart,name='mycart'),
    url(r'^(?P<cart_id>[0-9]+)/cart/delete$',views.delete_from_cart,name='delete_from_cart'),
    url(r'^(?P<p_id>[0-9]+)/view$',views.detail_view,name='detail_view'),
    url(r'^checkout/$',views.checkout,name='checkout'),
    url(r'^buynow/$',views.buynow,name='buynow'),

]

Desktop/Hackathon/HACKOVERFLOW/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from user_panel.models import Customer
from products.models import ProductData
import decimal
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductData,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1,null=True)
    total_price = models.DecimalField(null=True,decimal_places=2,max_digits=50)
    status = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
    	self.total_price = self.product.discounted_price * decimal.Decimal(self.quantity)
    	super(Cart,self).save(*args, **kwargs)


    def __str__(self):
    	return self.product.name + " " +str(self.total_price)

Desktop/Hackathon/HACKOVERFLOW/products/models.py
from django.db import models
import user_panel
from smart_selects.db_fields import ChainedForeignKey
import decimal


class CategoryData(models.Model):
	name = models.CharField( null=False , max_length=100)
	description = models.CharField(max_length=500,null=False)
	image = models.FileField()

	def __str__(self):
		return self.name


class SubCategoryData(models.Model):
	name = models.CharField( null=False , max_length=100)
	description = models.CharField(max_length=500,null=False)
	image = models.FileField()
	category = models.ForeignKey(CategoryData,on_delete=models.CASCADE)

	def __str__(self):
		return self.name


STATUS_CHOICES = (
    ('Kg', 'Kg'),
    ('gms', 'gms'),
    ('peices', 'peices'),
    ('packet', 'packet'),
    ('box', 'box'),
    ('Lt', 'Lt'),
    ('ml', 'ml'))




class ProductData(models.Model):
	name = models.CharField(null=False, max_length=500)
	description = models.CharField(max_length=500,null=False)
	category = models.ForeignKey(CategoryData,null=False,on_delete=models.CASCADE)
	image = models.FileField()
	sub_category_name = ChainedForeignKey(SubCategoryData, chained_field="category",
                                          chained_model_field="category", null=True)
	brand = models.CharField(null=True, max_length=100)
	mass = models.DecimalField(null=False,decimal_places=2,max_digits=50,default=1)
	unit = models.CharField(max_length=500, blank=False, null=False, default='Kg', choices=STATUS_CHOICES)
	available = models.BooleanField(default=False)
	price = models.DecimalField(null=True,decimal_places=2,max_digits=50)
	discount_percentage = models.DecimalField(null=True,decimal_places=2,max_digits=50)
	discounted_price = models.DecimalField(null=True,decimal_places=2,max_digits=50)
	reviews = models.ManyToManyField('user_panel.Review',blank=True)

	def __str__(self):
		return self.name
	def save(self, *args, **kwargs):
		x = float(self.price)
		y = float(self.discount_percentage)
		z = x - x*0.01*y
		self.discounted_price = decimal.Decimal(z)
		super(ProductData,self).save(*args, **kwargs)

Desktop/Hackathon/HACKOVERFLOW/cart/views.py
from django.shortcuts import render

from .models import Cart

Desktop/Hackathon/HACKOVERFLOW/products/views.py
from django.shortcuts import render,redirect
from .models import ProductData
from cart.models import Cart
from user_panel.models import Customer
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from django.views.decorators.csrf import csrf_exempt
from myorders.models import Order


def index(request):
	products = ProductData.objects.all()
	return render(request,'products/home.html',{'products':products})


@csrf_exempt
def add_to_cart(request):
	p_id = request.POST.get('p_id',False)
	print(p_id)
	customer = Customer.objects.get(user_id=request.user.id)
	# check if product already in cart
	x = Cart.objects.filter(product_id=p_id,customer_id=customer.id)
	print(len(x))
	if(len(x)):
		return HttpResponse("already in cart")

	# else add product to cart
	cart = Cart()
	
	cart.customer_id = customer.id 
	cart.product_id = p_id
	cart.save()
	print("Added to cart")
	return HttpResponse("success")

def mycart(request):
	if request.method=="GET":
		customer = Customer.objects.get(user_id=request.user.id)
		items = Cart.objects.filter(customer_id=customer.id)
		return render(request,'products/cart.html',{'items':items,'customer':customer})


def delete_from_cart(request,cart_id):
	print(cart_id)
	customer = Customer.objects.get(user_id=request.user.id)
	x = Cart.objects.get(id=cart_id,customer_id=customer.id)
	x.delete()
	return redirect('/products/mycart/')

def detail_view(request,p_id):
	print(p_id)
	return render(request,"products/detailed_product.html")


@csrf_exempt
def checkout(request):
	ids = list(request.POST.getlist('id[]'))
	quantities = list(request.POST.getlist('quantity[]'))
	for i in range(0,len(ids)):
		cart = Cart.objects.get(id=ids[i])
		cart.quantity = quantities[i]
		cart.save()
	return HttpResponse("success")

@csrf_exempt
def buynow(request):
	address = request.POST.get('address',False)
	customer = Customer.objects.get(user_id=request.user.id)
	carts = Cart.objects.filter(customer_id=customer.id)
	order = Order()
	order.customer_id = customer.id
	order.save()
	gtotal = 0
	for cart in carts:
		order.cart.add(cart)
		gtotal += cart.total_price
	order.grand_total = gtotal
	
	order.save()
	print("Order saved...")
	return HttpResponse("success")
	

Desktop/Hackathon/HACKOVERFLOW/templates/products/cart.html
<!DOCTYPE html>
<html>
<head>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<title>My Cart::Online Store</title>
	<style type="text/css">
		.table>tbody>tr>td, .table>tfoot>tr>td{
    vertical-align: middle;
}
@media screen and (max-width: 600px) {
    table#cart tbody td .form-control{
		width:20%;
		display: inline !important;
	}
	.actions .btn{
		width:36%;
		margin:1.5em 0;
	}
	
	.actions .btn-info{
		float:left;
	}
	.actions .btn-danger{
		float:right;
	}
	
	table#cart thead { display: none; }
	table#cart tbody td { display: block; padding: .6rem; min-width:320px;}
	table#cart tbody tr td:first-child { background: #333; color: #fff; }
	table#cart tbody td:before {
		content: attr(data-th); font-weight: bold;
		display: inline-block; width: 8rem;
	}
	
	
	
	table#cart tfoot td{display:block; }
	table#cart tfoot td .btn{display:block;}
	
}
	</style>
</head>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<body>
<div class="container">
	<h1 align="center">My Cart</h1>
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%">Product</th>
							<th style="width:10%">Price</th>
							<th style="width:8%">Quantity</th>
							<th style="width:22%" class="text-center">Subtotal</th>
							<th style="width:10%"></th>
						</tr>
					</thead>
					<form id="main">
					<tbody id="parent">
						{% for item in items %}
						<tr>
							<td data-th="Product">
								<div class="row">
									<div class="col-sm-2 hidden-xs"><img height="50px" width="50px" src="{{item.product.image.url}}"/></div>
									<div class="col-sm-10">
										<input type="hidden" value="{{ item.id }}">
										<h4 class="nomargin">{{item.product.name}}</h4>
										<p>{{item.product.description}}</p>
									</div>
								</div>
							</td>
								<!-- left -->

								<td data-th="Price" width="20%"><span>&#8377;&nbsp;</span>
									<span>{{ item.product.discounted_price }}</span></td>

							<td data-th="Quantity">
								<input type="number" onchange="update(this);"
onkeyup="this.onchange();" onpaste="this.onchange();" oninput="this.onchange();" value="{{item.quantity}}">
							</td>


							<td data-th="Subtotal" class="text-center">
								<span>&#8377;&nbsp;</span>
								<span>{{ item.total_price }}</span>
							</td>
							<td class="actions" data-th="">
								<button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
								<a href="{% url 'products:delete_from_cart' item.id %}"><button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>	</a>							
							</td>
						</tr>
						{% endfor %}
					</tbody>
					<tfoot>
						<tr class="visible-xs">
							<td class="text-center"><strong>Total </strong></td>
						</tr>
						<tr>
							<td><a href="{% url 'products:index' %}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td colspan="2" class="hidden-xs"></td>

							<td class="hidden-xs text-center">&#8377;&nbsp;<strong id="gTotal">0</strong></td>
							<td><a class="btn btn-success btn-block"><button type="submit">Checkout</button> <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>
			</form>
</div>


<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body" id="modal-text">
        <form id="address">
		    <div class="form-group">
		      <label class="control-label col-sm-2" for="review">Address </label>
		      <div class="col-sm-10">
		      <textarea class="form-control" id="addr" placeholder="Enter Address..">{{customer.address}}</textarea>
		      </div>
		    </div>
		    <div class="form-group">        
		      <div class="col-sm-offset-2 col-sm-10">
		        <button type="submit" class="btn btn-primary" >Place Order</button>
		      </div>
		    </div>
		  </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

</body>

<script type="text/javascript">
	$(document).ready(function(){
		var total = $('#gTotal');
		$('#gTotal').html(0);
		var table = $('#parent');
		$(table).children().each(function(){
			var current = Math.round(parseFloat($(total).html())*100)/100;
			var price = Math.round(parseFloat($(this).children().eq(3).children().eq(1).html())*100)/100;
			var x = Math.round((current+price)*100)/100;
			$(total).html(x);
		});	
	});
	function update(input){
		var left = $(input).parent().parent().children().eq(1).children().eq(1);
		var right = $(input).parent().parent().children().eq(3).children().eq(1);
		var y = $(input).val() * $(left).html();
		$(right).html(Math.round(y*100)/100);

		var table = $(input).parent().parent().parent();
		var total = $('#gTotal');
		$('#gTotal').html(0);
		$(table).children().each(function(){
			var current = Math.round(parseFloat($(total).html())*100)/100;
			var price = Math.round(parseFloat($(this).children().eq(3).children().eq(1).html())*100)/100;
			var x = Math.round((current+price)*100)/100;
			$(total).html(x);
		});	

	}
</script>
<script type="text/javascript">
	$('#main').submit(function(e){
		e.preventDefault();
		var table = $('#parent');
		var data = {'id':[],'quantity':[]};
		$(table).children().each(function(){
			var id = $(this).children().eq(0).children().eq(0).children().eq(1).children().eq(0);
			//console.log($(id).html());
			data['id'].push($(id).val());
			var quantity = $(this).children().eq(2).children().eq(0).val();
			data['quantity'].push(quantity);
		});	
		console.log(data);

		$.ajax({
			type: "POST",
			url: "/products/checkout/",
			data:data,
			success: function(data){
				console.log(data);
				$('#myModal').modal('show');
			}
		});

	});



	$('#address').submit(function(e){
		console.log($('#address').val());
		e.preventDefault();
		data = { 'address': $('#addr').val() }
		console.log(data);
		$.ajax({
			type: "POST",
			url: "/products/buynow/",
			data:data,
			success: function(data){
				console.log(data);
				
			}
		});

	});
</script>


</html>

Desktop/Hackathon/HACKOVERFLOW/templates/products/detailed_product.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <style>
        ul > li{margin-right:25px;font-weight:lighter;cursor:pointer}
li.active{border-bottom:3px solid silver;}

.item-photo{display:flex;justify-content:center;align-items:center;border-right:1px solid #f6f6f6;}
.menu-items{list-style-type:none;font-size:11px;display:inline-flex;margin-bottom:0;margin-top:20px}
.btn-success{width:100%;border-radius:0;}
.section{width:100%;margin-left:-15px;padding:2px;padding-left:15px;padding-right:15px;background:#f8f9f9}
.title-price{margin-top:30px;margin-bottom:0;color:black}
.title-attr{margin-top:0;margin-bottom:0;color:black;}
.btn-minus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-right:0;}
.btn-plus{cursor:pointer;font-size:7px;display:flex;align-items:center;padding:5px;padding-left:10px;padding-right:10px;border:1px solid gray;border-radius:2px;border-left:0;}
div.section > div {width:100%;display:inline-flex;}
div.section > div > input {margin:0;padding-left:5px;font-size:10px;padding-right:5px;max-width:18%;text-align:center;}
.attr,.attr2{cursor:pointer;margin-right:5px;height:20px;font-size:10px;padding:2px;border:1px solid gray;border-radius:2px;}
.attr.active,.attr2.active{ border:1px solid orange;}

@media (max-width: 426px) {
    .container {margin-top:0px !important;}
    .container > .row{padding:0 !important;}
    .container > .row > .col-xs-12.col-sm-5{
        padding-right:0 ;    
    }
    .container > .row > .col-xs-12.col-sm-9 > div > p{
        padding-left:0 !important;
        padding-right:0 !important;
    }
    .container > .row > .col-xs-12.col-sm-9 > div > ul{
        padding-left:10px !important;
        
    }            
    .section{width:104%;}
    .menu-items{padding-left:0;}
}
    </style>
</head>
    <body>
        <div class="container">
        	<div class="row">
               <div class="col-xs-4 item-photo">
                    <img style="max-width:100%;" src="https://ak1.ostkcdn.com/images/products/8818677/Samsung-Galaxy-S4-I337-16GB-AT-T-Unlocked-GSM-Android-Cell-Phone-85e3430e-6981-4252-a984-245862302c78_600.jpg" />
                </div>
                <div class="col-xs-5" style="border:0px solid gray">
                    <!-- Datos del vendedor y titulo del producto -->
                    <h3>Samsung Galaxy S4 I337 16GB 4G LTE Unlocked GSM Android Cell Phone</h3>    
                    <h5 style="color:#337ab7">vendido por <a href="#">Samsung</a> · <small style="color:#337ab7">(5054 ventas)</small></h5>
        
                    <!-- Precios -->
                    <h6 class="title-price"><small>PRECIO OFERTA</small></h6>
                    <h3 style="margin-top:0px;">U$S 399</h3>
        
                    <!-- Detalles especificos del producto -->
                    <div class="section">
                        <h6 class="title-attr" style="margin-top:15px;" ><small>COLOR</small></h6>                    
                        <div>
                            <div class="attr" style="width:25px;background:#5a5a5a;"></div>
                            <div class="attr" style="width:25px;background:white;"></div>
                        </div>
                    </div>
                    <div class="section" style="padding-bottom:5px;">
                        <h6 class="title-attr"><small>CAPACIDAD</small></h6>                    
                        <div>
                            <div class="attr2">16 GB</div>
                            <div class="attr2">32 GB</div>
                        </div>
                    </div>   
                    <div class="section" style="padding-bottom:20px;">
                        <h6 class="title-attr"><small>CANTIDAD</small></h6>                    
                        <div>
                            <div class="btn-minus"><span class="glyphicon glyphicon-minus"></span></div>
                            <input value="1" />
                            <div class="btn-plus"><span class="glyphicon glyphicon-plus"></span></div>
                        </div>
                    </div>                
        
                    <!-- Botones de compra -->
                    <div class="section" style="padding-bottom:20px;">
                        <button class="btn btn-success"><span style="margin-right:20px" class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Agregar al carro</button>
                        <h6><a href="#"><span class="glyphicon glyphicon-heart-empty" style="cursor:pointer;"></span> Agregar a lista de deseos</a></h6>
                    </div>                                        
                </div>                              
        
                <div class="col-xs-9">
                    <ul class="menu-items">
                        <li class="active">Detalle del producto</li>
                        <li>Garantía</li>
                        <li>Vendedor</li>
                        <li>Envío</li>
                    </ul>
                    <div style="width:100%;border-top:1px solid silver">
                        <p style="padding:15px;">
                            <small>
                            Stay connected either on the phone or the Web with the Galaxy S4 I337 from Samsung. With 16 GB of memory and a 4G connection, this phone stores precious photos and video and lets you upload them to a cloud or social network at blinding-fast speed. With a 17-hour operating life from one charge, this phone allows you keep in touch even on the go. 
        
                            With its built-in photo editor, the Galaxy S4 allows you to edit photos with the touch of a finger, eliminating extraneous background items. Usable with most carriers, this smartphone is the perfect companion for work or entertainment.
                            </small>
                        </p>
                        <small>
                            <ul>
                                <li>Super AMOLED capacitive touchscreen display with 16M colors</li>
                                <li>Available on GSM, AT T, T-Mobile and other carriers</li>
                                <li>Compatible with GSM 850 / 900 / 1800; HSDPA 850 / 1900 / 2100 LTE; 700 MHz Class 17 / 1700 / 2100 networks</li>
                                <li>MicroUSB and USB connectivity</li>
                                <li>Interfaces with Wi-Fi 802.11 a/b/g/n/ac, dual band and Bluetooth</li>
                                <li>Wi-Fi hotspot to keep other devices online when a connection is not available</li>
                                <li>SMS, MMS, email, Push Mail, IM and RSS messaging</li>
                                <li>Front-facing camera features autofocus, an LED flash, dual video call capability and a sharp 4128 x 3096 pixel picture</li>
                                <li>Features 16 GB memory and 2 GB RAM</li>
                                <li>Upgradeable Jelly Bean v4.2.2 to Jelly Bean v4.3 Android OS</li>
                                <li>17 hours of talk time, 350 hours standby time on one charge</li>
                                <li>Available in white or black</li>
                                <li>Model I337</li>
                                <li>Package includes phone, charger, battery and user manual</li>
                                <li>Phone is 5.38 inches high x 2.75 inches wide x 0.13 inches deep and weighs a mere 4.59 oz </li>
                            </ul>  
                        </small>
                    </div>
                </div>		
            </div>
        </div>        
    </body>
</html>

Desktop/Hackathon/HACKOVERFLOW/templates/products/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Online Shopping::FARMERS</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<style>
.productbox {
    background-color:#ffffff;
	padding:10px;
	margin-bottom:10px;
	-webkit-box-shadow: 0 8px 6px -6px  #999;
	   -moz-box-shadow: 0 8px 6px -6px  #999;
	        box-shadow: 0 8px 6px -6px #999;
}

.producttitle {
    font-weight:bold;
	padding:5px 0 5px 0;
}

.productprice {
	border-top:1px solid #dadada;
	padding-top:5px;
}

.pricetext {
	font-weight:bold;
	font-size:1.4em;
}
</style>
<body>
<div class="pull-right"><a href="{% url 'products:mycart' %}" class="btn btn-primary btn-lg" role="button" style="margin: 10px">My Cart</a></div>
    
{% for p in products %}

<div class="col-md-3 column productbox">
	<a href="{% url 'products:detail_view' p.id %}">
    <img src="{{p.image.url}}" class="img-responsive">
	</a>
    <div class="producttitle">{{p.name}}</div>
    <div class="productprice">
    	<br>
    	 <div class="pricetext">&#8377; <strike>{{p.price}}</strike> {{p.discounted_price}}</div></div><br><br>
    <div class="pull-left"><a href="#" class="btn btn-primary btn-sm" role="submit">BUY</a></div>
    <span>&nbsp;&nbsp;</span>
    <div class="pull-left"><a onclick="add_to_cart({{p.id}})" class="btn btn-danger btn-sm" role="submit">Add to Cart</a></div>
 </div>  
</div>

{% endfor %}




<button type="button" class="btn btn-info btn-lg" onclick="model();" data-toggle="modal" data-target="#myModal">Open Modal</button>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body" id="modal-text">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>





</body>



<script>
	function add_to_cart(p_id){
		
		$.ajax({
				type: "POST",
				url: '/products/add_to_cart/',
				data: { 'p_id':p_id
						},
				success: function(data){
					if(data=="success"){ alert("Success! Added to Cart."); }
					else{ alert("Already in Cart!"); }
					
				},
				error:  function(){
					alert("THere was some error.");
				}
		});
	}


</script>


<script type="text/javascript">
	function model(){
		var url = "http://127.0.0.1:8000/chat";
		var res = httpGet(url);
		$('#modal-text').html(res);
	}
</script>


<script type="text/javascript">
	var url = "http://127.0.0.1:8000/user_panel/chatbot";
	//httpGet(url);
	function httpGet(url)
		{
		    var xmlHttp = new XMLHttpRequest();
		    xmlHttp.open( "GET", url, false ); // false for synchronous request
		    xmlHttp.send( null );
		    return xmlHttp.responseText;
		}
</script>
</html>