Desktop/Hackathon/HACKOVERFLOW/NACOF/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^user_panel/', include('user_panel.urls')),
    url(r'^member_panel/', include('member_panel.urls')),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^cart/',include('cart.urls')),
    url(r'^myorders/',include('myorders.urls'))

]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/Hackathon/HACKOVERFLOW/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    
]

Desktop/Hackathon/HACKOVERFLOW/myorders/urls.py
from django.conf.urls import url
app_name = 'myorders'

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
     url(r'^(?P<bill_id>[0-9]+)$', views.detail, name='detail'),
     url(r'^(?P<p_id>[0-9]+)/review$', views.review, name='review'),
    
    
    # url used to process the xmlhttprequests done by nodejs socket.io
    
]

Desktop/Hackathon/HACKOVERFLOW/myorders/models.py
from django.db import models
from cart.models import Cart
import user_panel

import random

class Order(models.Model):
	cart = models.ManyToManyField(Cart,blank=True)
	bill = models.CharField(max_length=50,null=False)
	customer = models.ForeignKey("user_panel.Customer",on_delete=models.CASCADE,null=True,default=1)
	grand_total = models.DecimalField(null=True,decimal_places=2,max_digits=50)
	modified = models.DateTimeField(auto_now=True, auto_now_add=False)
	created = models.DateTimeField(auto_now=False, auto_now_add=True)
	status = models.IntegerField(null=True,default=0)
	bill_generated = models.BooleanField(default=False)

	def __str__(self):
		return str(self.bill)
	def get_cart(self):
		return "\n".join([str(p) for p in self.cart.all()])

	def save(self, *args, **kwargs):
		super(Order,self).save(*args, **kwargs)
		self.grand_total = 0
		for obj in self.cart.all():
			self.grand_total += obj.total_price
			print("increment ",obj.total_price)
		if not self.bill_generated:
			self.bill = str(random.randint(10000000,99999999)) + str(self.id)
			self.bill_generated = 1
		
			
		super(Order,self).save(*args, **kwargs)




class Delivery(models.Model):
	order = models.ForeignKey('Order',on_delete=models.CASCADE)
	location = models.CharField(max_length=100,null=True)
	time_left = models.CharField(max_length=100,null=True)

Desktop/Hackathon/HACKOVERFLOW/myorders/views.py
from django.shortcuts import render
from .models import Order,Delivery
from cart.models import Cart
from user_panel.models import Review,Customer
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from products.models import ProductData
from django.views.decorators.csrf import csrf_exempt

def index(request):
	orders = Order.objects.filter(customer__user_id=request.user.id)
	return render(request,'myorders/index.html',{ "orders":orders })

def detail(request,bill_id):
	order = Order.objects.get(bill=bill_id)
	cart = order.cart.all()
	try:
		delivery = Delivery.objects.get(order__bill=bill_id)
	except:
		return render(request,'myorders/detail.html',{ "order":order,"cart":cart,'delivery':[],'msg':"Not yet dispactched" })

	return render(request,'myorders/detail.html',{ "order":order,"cart":cart,'delivery':delivery })

@csrf_exempt
def review(request,p_id):
	if request.method =='GET':
		return render(request,'myorders/review.html')
	else:
		try:
			review = Review()
			review.description = request.POST.get('review',False)	
			customer = Customer.objects.get(user_id=request.user.id)
			review.customer_id = customer.id
			review.save()
			product = ProductData.objects.get(id=p_id)
			product.reviews.add(review)
			product.save()
			return HttpResponse('success')
		except:
			return HttpResponse('error')

Desktop/Hackathon/HACKOVERFLOW/templates/myorders/detail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript">
  	{% if msg %}
  	alert("{{msg}}");
  	{% endif %}
  </script>
</head>
<body>
<h2>Bill No {{order.bill}} </h2><span>placed at {{order.created}}</span>
<br>
<h4>Total {{order.grand_total}}</h4>
{% for c in cart %}
<div class="col-sm-6">
	<div class="row">
	<div class="col-sm-6">
	<img src="{{c.product.image.url}}" class="img-responsive">
	<button type="submit" class="btn btn-info btn-lg" data-toggle="modal" onclick="modal_fired('{{c.product.id}}','{{c.product.name}}')" data-target="#myModal">Review It</button>
</div>
<div class="col-sm-4">
	<p style="">{{c.product.name}}</p>
<p>{{c.quantity}}</p>
<p>{{c.total_price}}</p>
</div>	
</div>
</div>
{% endfor %}
<div class="col-sm-8">
	<div class="row">
		<h2>Delivery Tracking</h2>
		<p>Status: {{delivery.location}}</p>
		<p>Estimated Time Left: {{delivery.time_left}}</p>
	</div>
</div>

	<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">{{order.customer.FirstName}} - </h4><h5 id="name"></h5>
        </div>
        <div class="modal-body">
          <form class="form-horizontal">
    <div class="form-group">
      <label class="control-label col-sm-2" for="review">Review:</label>
      <div class="col-sm-10">
      <textarea class="form-control" id="review" placeholder="Enter Review"></textarea>
      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</body>
<script type="text/javascript">
	var id=1;
	function modal_fired(pid,pname){
		
		id=pid;
		$('#name').html(pname);
	};
	$('form').submit(function(e){
		console.log("post request");
		e.preventDefault();
		data = {'review': $('#review').val(),
				  'pid':id};
		console.log(data);

		if($('#review').val()=='')
		alert ("Empty");
		else
		{
			$.ajax({
			type: "POST",
			url: "/myorders/"+id+"/review",
			data:data,
			success: function(data){
				$('#review').text("");
				console.log(data);	
				if(data=="success")
					alert("Review Recorded");
				else
					alert("Error Occured");
			}
		});
		}
	});
</script>
</html>

Desktop/Hackathon/HACKOVERFLOW/templates/myorders/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Online Shopping::FARMERS</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<style>
.productbox {
    background-color:#ffffff;
	padding:10px;
	margin-bottom:10px;
	-webkit-box-shadow: 0 8px 6px -6px  #999;
	   -moz-box-shadow: 0 8px 6px -6px  #999;
	        box-shadow: 0 8px 6px -6px #999;
}

.producttitle {
    font-weight:bold;
	padding:5px 0 5px 0;
}

.productprice {
	border-top:1px solid #dadada;
	padding-top:5px;
}

.pricetext {
	font-weight:bold;
	font-size:1.4em;
}
</style>
<body>

    
{% for p in orders %}

<div class="col-md-3 column productbox">
    
    <div class="producttitle">{{p.bill}}</div>
    <div class="producttitle">{{p.created}}</div>
        <div class="producttitle">{{p.grand_total}}</div>
         <div class="producttitle">{{p.cart.count}}</div>
         {% if p.status == 0 %}
         <div class="producttitle">Order Placed</div>
         {%endif%}
         {% if p.status == 1 %}
         <div class="producttitle">Order Dispatched</div>
         {%endif%}
         {% if p.status == 2 %}
         <div class="producttitle">Order Delivered</div>
         {%endif%}


         <div><a href="{%url 'myorders:detail' p.bill %}" class="btn btn-primary">Details</a></div>

    <div class="productprice">
    	<br>
   </div>
 </div>  
</div>

{% endfor %}
</body>




</html>